name: qlmoney
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  connectivity_plus: ^7.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  firebase_storage: ^13.0.2
  font_awesome_flutter: ^10.7.0
  cloud_firestore: ^6.0.2
  dotted_border: ^3.1.0
  intl: 0.20.2
  flutter_colorpicker: ^1.0.3
  carousel_slider: ^5.1.1
  flutter_bloc: ^9.1.1
  ionicons: ^0.2.2
  table_calendar: ^3.1.1
  curved_navigation_bar: ^1.0.3
  fl_chart: ^1.1.1
  pie_chart: ^5.4.0
  syncfusion_flutter_charts: ^31.1.23
  file_picker: ^10.3.3
  image_picker: ^1.2.0
  image_picker_for_web: ^3.1.0
  universal_io: ^2.2.2
  month_picker_dialog: ^6.5.0
  flutter_spinkit: ^5.1.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.2
  awesome_notifications: ^0.10.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  google_sign_in: ^7.2.0
  chat_gpt_sdk: ^3.1.5
  http: ^1.2.1
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/food.png
    - assets/image/salary.png
    - assets/image/add.jpg
    - assets/image/
    - assets/icons/
    - assets/translations/